In [240]:
import pandas as pd
from scipy.stats import zscore

In [69]:
df = pd.read_csv('/Users/umarsharif/SQL/Arrest_Data_from_2010_to_Present.csv')

In [73]:
df

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,date
0,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)",2019-05-03
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)",2019-04-29
2,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)",2019-04-30
3,5615701,04/30/2019,1100.0,9,Van Nuys,901,2,F,H,NaN,NaN,D,300(B)WIC,NaN,RAYMER,SEPULVEDA BL,"(34.2149, -118.4674)",2019-04-30
4,5615929,04/30/2019,1550.0,20,Olympic,2049,41,M,W,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,8TH ST,VERMONT,"(34.0578, -118.2916)",2019-04-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310122,5612927,04/27/2019,2355.0,21,Topanga,2125,22,M,H,22.0,Driving Under Influence,M,23152(G)VC,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)",2019-04-27
1310123,5612964,04/27/2019,1829.0,1,Central,161,30,M,W,8.0,Other Assaults,F,69PC,OBSTRUCT/RESIST EXECUTIVE OFFICER,HARBOR FY,4TH ST,"(34.0483, -118.2631)",2019-04-27
1310124,5612940,04/27/2019,2315.0,17,Devonshire,1797,42,M,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,8500 RUBIO AV,NaN,"(34.2248, -118.4967)",2019-04-27
1310125,5612654,04/27/2019,1555.0,18,Southeast,1832,38,F,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,100 E 104TH ST,NaN,"(33.942, -118.2739)",2019-04-27
1310126,5612691,04/27/2019,1545.0,12,77th Street,1203,32,F,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",1600 W 52ND ST,NaN,"(33.9994, -118.3108)",2019-04-27

In [71]:
df['date'] = pd.to_datetime(df['Arrest Date'])

In [72]:
df.date

0         2019-05-03
1         2019-04-29
2         2019-04-30
3         2019-04-30
4         2019-04-30
             ...
1310122   2019-04-27
1310123   2019-04-27
1310124   2019-04-27
1310125   2019-04-27
1310126   2019-04-27
Name: date, Length: 1310127, dtype: datetime64[ns]

In [209]:
#question 1
df[(df.date<'2019-01-01') & (df.date>'2017-12-31')].count()

Report ID                   104277
Arrest Date                 104277
Time                        104270
Area ID                     104277
Area Name                   104277
Reporting District          104277
Age                         104277
Sex Code                    104277
Descent Code                104277
Charge Group Code            91890
Charge Group Description     91814
Arrest Type Code            104277
Charge                      104277
Charge Description           91890
Address                     104277
Cross Street                 56333
Location                    104277
date                        104277
year                        104277
dtype: int64

In [107]:
#question 2
df[(df.date<'2019-01-01') & (df.date>'2017-12-31')].groupby('Area Name').size().max()

10951

In [96]:
df['Age'].quantile(.95)

58.0

In [119]:
#question 3
df[ ((df.date<'2019-01-01') & (df.date>'2017-12-31')) &
    ((df['Charge Group Description']=='Homicide') | (df['Charge Group Description']=='Burglary') | 
  (df['Charge Group Description']=='Vehicle Theft') | 
     (df['Charge Group Description']=='Receive Stolen Property'))]['Age'].quantile(.95)

52.0

In [130]:
df['Charge Group Description'].unique().tolist()

[nan,
 'Robbery',
 'Burglary',
 'Aggravated Assault',
 'Miscellaneous Other Violations',
 'Drunkeness',
 'Larceny',
 'Liquor Laws',
 'Narcotic Drug Laws',
 'Disorderly Conduct',
 'Prostitution/Allied',
 'Disturbing the Peace',
 'Driving Under Influence',
 'Gambling',
 'Sex (except rape/prst)',
 'Fraud/Embezzlement',
 'Receive Stolen Property',
 'Other Assaults',
 'Homicide',
 'Weapon (carry/poss)',
 'Vehicle Theft',
 'Against Family/Child',
 'Forgery/Counterfeit',
 'Moving Traffic Violations',
 'Non-Criminal Detention',
 'Rape',
 'Federal Offenses',
 'Pre-Delinquency']

In [131]:
df['year'] = pd.DatetimeIndex(df['date']).year

In [132]:
df.year

0          2019
1          2019
2          2019
3          2019
4          2019
           ...
1310122    2019
1310123    2019
1310124    2019
1310125    2019
1310126    2019
Name: year, Length: 1310127, dtype: int64

In [136]:
df[df['Charge Group Description']=='Robbery'].groupby('year').size()

year
2010    3227
2011    3125
2012    2713
2013    2387
2014    2278
2015    2458
2016    2624
2017    2816
2018    2787
2019    2282
dtype: int64

In [140]:
#Question 4
df.dtypes

Report ID                            int64
Arrest Date                         object
Time                               float64
Area ID                              int64
Area Name                           object
Reporting District                   int64
Age                                  int64
Sex Code                            object
Descent Code                        object
Charge Group Code                  float64
Charge Group Description            object
Arrest Type Code                    object
Charge                              object
Charge Description                  object
Address                             object
Cross Street                        object
Location                            object
date                        datetime64[ns]
year                                 int64
dtype: object

In [148]:
# Question 8
#dropping NaN on 'Charge Group Code' and saving it in new dataframe ndf
ndf = df.dropna(subset=['Charge Group Code'])
ndf

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,date,year
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)",2019-04-29,2019
2,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)",2019-04-30,2019
4,5615929,04/30/2019,1550.0,20,Olympic,2049,41,M,W,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,8TH ST,VERMONT,"(34.0578, -118.2916)",2019-04-30,2019
5,190112234,04/16/2019,1450.0,1,Central,123,54,F,H,24.0,Miscellaneous Other Violations,M,41.45CLAMC,ILLEGAL POSSESSION OF SHOPPING CART,1ST,SPRING,"(34.053, -118.2444)",2019-04-16,2019
6,190112235,04/26/2019,1505.0,1,Central,152,57,M,H,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,6TH,HILL,"(34.0481, -118.2542)",2019-04-26,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310122,5612927,04/27/2019,2355.0,21,Topanga,2125,22,M,H,22.0,Driving Under Influence,M,23152(G)VC,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)",2019-04-27,2019
1310123,5612964,04/27/2019,1829.0,1,Central,161,30,M,W,8.0,Other Assaults,F,69PC,OBSTRUCT/RESIST EXECUTIVE OFFICER,HARBOR FY,4TH ST,"(34.0483, -118.2631)",2019-04-27,2019
1310124,5612940,04/27/2019,2315.0,17,Devonshire,1797,42,M,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,8500 RUBIO AV,NaN,"(34.2248, -118.4967)",2019-04-27,2019
1310125,5612654,04/27/2019,1555.0,18,Southeast,1832,38,F,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,100 E 104TH ST,NaN,"(33.942, -118.2739)",2019-04-27,2019
1310126,5612691,04/27/2019,1545.0,12,77th Street,1203,32,F,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",1600 W 52ND ST,NaN,"(33.9994, -118.3108)",2019-04-27,2019

In [166]:
# dropping 99.0 and all dates including & after 2019-01-01
ndf=ndf[(ndf['date']<'2019-01-1') & (ndf['Charge Group Code']!=99.0)]

In [165]:
ndf["Charge Group Code"].unique()

array([10., 11.,  8.,  1., 16., 12., 24.,  7.,  4., 22.,  3.,  5., 15.,
        6., 23.,  9., 13., 14., 17., 18.,  2., 19., 26., 27., 29., 21.,
       20., 25.])

In [178]:
ndf.groupby(['Area ID','Charge Group Code']).size()

Area ID  Charge Group Code
1        1.0                   133
         2.0                   188
         3.0                  1530
         4.0                  4254
         5.0                  1034
                              ...
21       24.0                 6608
         25.0                    7
         26.0                  229
         27.0                  763
         29.0                    2
Length: 588, dtype: int64

In [177]:
ndf.groupby(['Area ID']).size()

Area ID
1     116368
2      56184
3      63703
4      37985
5      44126
6     102986
7      29067
8      25864
9      61337
10     36261
11     46219
12     65701
13     63482
14     74641
15     56024
16     43617
17     36660
18     45266
19     58456
20     47108
21     40658
dtype: int64

In [187]:
ratio_chargebyarea = ndf.groupby(['Area ID','Charge Group Code']).size()/ndf.groupby(['Area ID']).size()

In [205]:
ratio_chargebyarea*100

Area ID  Charge Group Code
1        1.0                   0.114293
         2.0                   0.161556
         3.0                   1.314794
         4.0                   3.655644
         5.0                   0.888560
                                ...
21       24.0                 16.252644
         25.0                  0.017217
         26.0                  0.563235
         27.0                  1.876629
         29.0                  0.004919
Length: 588, dtype: float64

In [184]:
ndf.groupby('Charge Group Code').size()

Charge Group Code
1.0       2255
2.0       2714
3.0      24415
4.0      77964
5.0      22726
6.0      66257
7.0      22723
8.0      56650
9.0       6683
10.0      8890
11.0      6358
12.0     28403
13.0     36780
14.0     12606
15.0      6501
16.0    153432
17.0     49222
18.0    113420
19.0      2878
20.0     36264
21.0      2062
22.0    112996
23.0     50471
24.0    229826
25.0       215
26.0      6697
27.0     11853
29.0       452
dtype: int64

In [185]:
ndf['Charge Group Code'].count()

1151713

In [188]:
ratio_chargetotal = ndf.groupby('Charge Group Code').size()/ndf['Charge Group Code'].count()

In [196]:
ratio_chargetotal*100

Charge Group Code
1.0      0.195795
2.0      0.235649
3.0      2.119886
4.0      6.769395
5.0      1.973235
6.0      5.752909
7.0      1.972974
8.0      4.918760
9.0      0.580266
10.0     0.771894
11.0     0.552047
12.0     2.466153
13.0     3.193504
14.0     1.094544
15.0     0.564464
16.0    13.322069
17.0     4.273808
18.0     9.847940
19.0     0.249889
20.0     3.148701
21.0     0.179038
22.0     9.811125
23.0     4.382255
24.0    19.955145
25.0     0.018668
26.0     0.581482
27.0     1.029163
29.0     0.039246
dtype: float64

In [189]:
ratio_chargebyarea/ratio_chargetotal

Area ID  Charge Group Code
1        1.0                  0.583735
         2.0                  0.685581
         3.0                  0.620219
         4.0                  0.540025
         5.0                  0.450307
                                ...
21       24.0                 0.814459
         25.0                 0.922269
         26.0                 0.968620
         27.0                 1.823453
         29.0                 0.125340
Length: 588, dtype: float64

In [207]:
ratio = ratio_chargebyarea/ratio_chargetotal
ratio.nlargest(5)
ratio.nlargest(5).mean()

3.515076379865202

In [211]:
#question 4
df4= df.dropna(subset=['Charge Group Description'])
df4

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,date,year
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)",2019-04-29,2019
2,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)",2019-04-30,2019
4,5615929,04/30/2019,1550.0,20,Olympic,2049,41,M,W,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,8TH ST,VERMONT,"(34.0578, -118.2916)",2019-04-30,2019
5,190112234,04/16/2019,1450.0,1,Central,123,54,F,H,24.0,Miscellaneous Other Violations,M,41.45CLAMC,ILLEGAL POSSESSION OF SHOPPING CART,1ST,SPRING,"(34.053, -118.2444)",2019-04-16,2019
6,190112235,04/26/2019,1505.0,1,Central,152,57,M,H,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,6TH,HILL,"(34.0481, -118.2542)",2019-04-26,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310122,5612927,04/27/2019,2355.0,21,Topanga,2125,22,M,H,22.0,Driving Under Influence,M,23152(G)VC,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)",2019-04-27,2019
1310123,5612964,04/27/2019,1829.0,1,Central,161,30,M,W,8.0,Other Assaults,F,69PC,OBSTRUCT/RESIST EXECUTIVE OFFICER,HARBOR FY,4TH ST,"(34.0483, -118.2631)",2019-04-27,2019
1310124,5612940,04/27/2019,2315.0,17,Devonshire,1797,42,M,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,8500 RUBIO AV,NaN,"(34.2248, -118.4967)",2019-04-27,2019
1310125,5612654,04/27/2019,1555.0,18,Southeast,1832,38,F,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,100 E 104TH ST,NaN,"(33.942, -118.2739)",2019-04-27,2019
1310126,5612691,04/27/2019,1545.0,12,77th Street,1203,32,F,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",1600 W 52ND ST,NaN,"(33.9994, -118.3108)",2019-04-27,2019

In [213]:
df4 = df4[(df4.date<'2019-01-01') & (df.date>'2017-12-31') & 
        (df4['Charge Group Description']!='Pre-Delinquency') 
        & (df4['Charge Group Description']!='Non-Criminal Detention')]

/Users/umarsharif/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

In [222]:
avg_age = df4.groupby(['Charge Group Description'])['Age'].mean()

In [223]:
avg4 = avg_age.mean()
avg4

34.8977955199648

In [224]:
std4 = avg_age.std()
std4

4.232974453466987

In [227]:
z = (avg_age-avg4)/std4
z

Charge Group Description
Against Family/Child              0.151607
Aggravated Assault               -0.109420
Burglary                         -1.064637
Disorderly Conduct                1.495897
Disturbing the Peace              0.971517
Driving Under Influence           0.013125
Drunkeness                        2.127870
Federal Offenses                 -0.193196
Forgery/Counterfeit              -0.149478
Fraud/Embezzlement                0.169541
Gambling                          1.514485
Homicide                         -1.045835
Larceny                          -0.264880
Liquor Laws                       1.792046
Miscellaneous Other Violations    0.151168
Moving Traffic Violations        -0.241717
Narcotic Drug Laws                0.332050
Other Assaults                   -0.190524
Prostitution/Allied              -1.155626
Rape                              0.063893
Receive Stolen Property          -0.733902
Robbery                          -1.822549
Sex (except rape/prst)            0.503639
Vehicle Theft                    -1.199199
Weapon (carry/poss)              -1.115876
Name: Age, dtype: float64

In [230]:
z.max()

2.1278699344353633

In [231]:
df

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,date,year
0,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)",2019-05-03,2019
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)",2019-04-29,2019
2,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)",2019-04-30,2019
3,5615701,04/30/2019,1100.0,9,Van Nuys,901,2,F,H,NaN,NaN,D,300(B)WIC,NaN,RAYMER,SEPULVEDA BL,"(34.2149, -118.4674)",2019-04-30,2019
4,5615929,04/30/2019,1550.0,20,Olympic,2049,41,M,W,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,8TH ST,VERMONT,"(34.0578, -118.2916)",2019-04-30,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310122,5612927,04/27/2019,2355.0,21,Topanga,2125,22,M,H,22.0,Driving Under Influence,M,23152(G)VC,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)",2019-04-27,2019
1310123,5612964,04/27/2019,1829.0,1,Central,161,30,M,W,8.0,Other Assaults,F,69PC,OBSTRUCT/RESIST EXECUTIVE OFFICER,HARBOR FY,4TH ST,"(34.0483, -118.2631)",2019-04-27,2019
1310124,5612940,04/27/2019,2315.0,17,Devonshire,1797,42,M,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,8500 RUBIO AV,NaN,"(34.2248, -118.4967)",2019-04-27,2019
1310125,5612654,04/27/2019,1555.0,18,Southeast,1832,38,F,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,100 E 104TH ST,NaN,"(33.942, -118.2739)",2019-04-27,2019
1310126,5612691,04/27/2019,1545.0,12,77th Street,1203,32,F,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",1600 W 52ND ST,NaN,"(33.9994, -118.3108)",2019-04-27,2019

In [232]:
# Question 5
df5 = df[(df['Charge Group Description']=='Burglary') | (df['Charge Group Description']=='Homicide') |
        (df['Charge Group Description']=='Larceny') |(df['Charge Group Description']=='Rape') |
        (df['Charge Group Description']=='Robbery') |(df['Charge Group Description']=='Vehicle Theft') |
        (df['Charge Group Description']=='Weapon (carry/poss)') |(df['Charge Group Description']=='Aggravated Assault') |
        (df['Charge Group Description']=='Narcotic Drug Laws') |(df['Charge Group Description']=='Forgery/Counterfeit') |
        (df['Charge Group Description']=='')]
df5

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,date,year
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)",2019-04-29,2019
2,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)",2019-04-30,2019
4,5615929,04/30/2019,1550.0,20,Olympic,2049,41,M,W,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,8TH ST,VERMONT,"(34.0578, -118.2916)",2019-04-30,2019
8,190112237,04/26/2019,1845.0,1,Central,162,29,M,B,6.0,Larceny,M,459.5PC,SHOPLIFTING,700 W 7TH ST,NaN,"(34.048, -118.2577)",2019-04-26,2019
58,190210441,04/27/2019,1220.0,2,Rampart,271,46,F,K,16.0,Narcotic Drug Laws,M,11377(A)HS,POSSESSION CONTROLLED SUBSTANCE,CARONDELET ST,7TH ST,"(34.0529, -118.2819)",2019-04-27,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310119,5612854,04/27/2019,1910.0,4,Hollenbeck,456,43,M,H,16.0,Narcotic Drug Laws,F,11378HS,POSSESSION CONTROLLED SUBSTANCE FOR SALE,FICKETT,MALABAR,"(34.0499, -118.2033)",2019-04-27,2019
1310120,5612887,04/27/2019,2145.0,16,Foothill,1684,36,M,B,4.0,Aggravated Assault,F,243(D)PC,BATTERY W/GBI,LANKERSHIM,STAGG,"(34.2121, -118.3878)",2019-04-27,2019
1310124,5612940,04/27/2019,2315.0,17,Devonshire,1797,42,M,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,8500 RUBIO AV,NaN,"(34.2248, -118.4967)",2019-04-27,2019
1310125,5612654,04/27/2019,1555.0,18,Southeast,1832,38,F,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,100 E 104TH ST,NaN,"(33.942, -118.2739)",2019-04-27,2019
1310126,5612691,04/27/2019,1545.0,12,77th Street,1203,32,F,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",1600 W 52ND ST,NaN,"(33.9994, -118.3108)",2019-04-27,2019

In [238]:
yearly_data = df5[(df5.date<'2019-01-01') & (df.date>'2009-12-31')].groupby('year').size()

/Users/umarsharif/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [242]:
yearly_data

year
2010    54280
2011    49709
2012    50553
2013    48208
2014    46447
2015    40659
2016    41062
2017    39195
2018    37459
dtype: int64